# Generated by Django 6.1.1 on 2026-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL')], max_length=100, null=True)),
                ('course_image', models.ImageField(null=True, upload_to='media/course_image')),
                ('course_fee', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
